### DISCUSSION TITLE
Feature Request: More than one disable_entity: ... I.e. disable_entities: and a list of entities?

### DISCUSSION THREAD

**Discussion by danielbrunt57** [jseidl/magic-areas#180] [Ideas / Feature Requests]
Been trying to figure out how to deploy Magic Areas for my living room such that:
1. Use my living room motion sensor to turn just the fireplace light on/off only at night - done & working.
2. Use my living room TV to keep the fireplace light from turning off - done & working.
3. Be able to manually turn on either the pole lamp or the living room lamp so I can read, etc. AND disable the automatic light fireplace light from turning on/off when presence is sensed/cleared?  I tried turning on presence_hold in an automation but that turns the fireplace light on.  I've created the following templated override entity but it would be nice if Magic Areas supported a `disable_entities:` list.
```
      living_room_motion_override:
        unique_id: "living-room-motion-override"
        friendly_name: "Living Room Motion Override"
        value_template: "{{ is_state('binary_sensor.south_patio_lux_override', 'on') or is_state('input_boolean.living_room_automatic_lights_disabled', 'on') or is_state('light.pole_lamp', 'on') or is_state('light.living_room_light', 'on') }}"
```
