### DISCUSSION TITLE
User-override occupancy switch for each area

### DISCUSSION THREAD

**Discussion by klatka** [jseidl/magic-areas#280] [Ideas / Feature Requests]
If a person clicks on the button "turn on lights" of a dimmer for a specific area, MA should consider this area as occupied.
To do that I manually created a `input_boolean` and a template `binary_sensor` for each area with a dimmer:

```
input_boolean:
  area_occupancy_user_area1:
    name: Occupy area1
    icon: mdi:location-enter

template:
  - binary_sensor:
      - unique_id: area_occupancy_user_area1
        attributes:
          friendly_name: "Area1 occupied"
        icon: mdi:location-enter
        device_class: occupancy
        state: >-
          {{ states('input_boolean.area_occupancy_user_area1') }}
```

Because of device class `occupancy`, this binary sensor is seen by MA.

Compared to presence hold switch this would be another great feature.
